PRAGMA encoding="UTF-8";
PRAGMA foreign_keys = ON;


DROP TABLE IF EXISTS FORMA;
DROP TABLE IF EXISTS CONJUGACAO;
DROP TABLE IF EXISTS PESSOA;
DROP TABLE IF EXISTS VERBO;
DROP TABLE IF EXISTS TEMPO;
DROP TABLE IF EXISTS MODO;

CREATE TABLE MODO (
    ID INTEGER PRIMARY KEY,
    CODIGO TEXT UNIQUE NOT NULL,
    DESCRICAO TEXT NOT NULL
);

CREATE TABLE TEMPO (
    ID INTEGER PRIMARY KEY,
    CODIGO TEXT UNIQUE NOT NULL,
    DESCRICAO TEXT NOT NULL,
    IDMODO INTEGER,
    TEXTOFORMATO TEXT,
    FOREIGN KEY(IDMODO) REFERENCES MODO(ID)
);

CREATE TABLE VERBO (
    ID INTEGER PRIMARY KEY,
    CODIGO TEXT UNIQUE NOT NULL,
    DESCRICAO TEXT NOT NULL
);

CREATE TABLE PESSOA (
    ID INTEGER PRIMARY KEY,
    ORDEM INTEGER NOT NULL,
    CODIGO TEXT UNIQUE NOT NULL,
    DESCRICAO TEXT NOT NULL
);

CREATE TABLE CONJUGACAO (
    ID INTEGER PRIMARY KEY,
    IDVERBO INTEGER NOT NULL,
    IDTEMPO INTEGER NOT NULL,
    UNIQUE(IDVERBO, IDTEMPO),
    FOREIGN KEY(IDVERBO) REFERENCES VERBO(ID) ON DELETE CASCADE,
    FOREIGN KEY(IDTEMPO) REFERENCES TEMPO(ID)
);

CREATE TABLE FORMA (
    ID INTEGER PRIMARY KEY,
    IDCONJUGACAO INTEGER NOT NULL,
    IDPESSOA INTEGER,
    TEXTO TEXT NOT NULL,
    FOREIGN KEY(IDCONJUGACAO) REFERENCES CONJUGACAO(ID) ON DELETE CASCADE,
    FOREIGN KEY(IDPESSOA) REFERENCES PESSOA(ID)
);
