INSERT INTO VERBO(ID, CODIGO, DESCRICAO)
VALUES(1, 'SER', 'Ser');

INSERT INTO CONJUGACAO (ID,IDVERBO,IDTEMPO)
VALUES(1, 1, 1);

INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(1, 1, 'sou');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(1, 2, 'és');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(1, 3, 'é');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(1, 4, 'somos');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(1, 5, 'sois');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(1, 6, 'são');


INSERT INTO CONJUGACAO (ID,IDVERBO,IDTEMPO)
VALUES(2, 1, 2);

INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(2, 1, 'era');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(2, 2, 'eras');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(2, 3, 'era');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(2, 4, 'éramos');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(2, 5, 'éreis');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(2, 6, 'eram');


INSERT INTO CONJUGACAO (ID,IDVERBO,IDTEMPO)
VALUES(3, 1, 3);

INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(3, 1, 'fui');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(3, 2, 'foste');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(3, 3, 'foi');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(3, 4, 'fomos');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(3, 5, 'fostes');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(3, 6, 'foram');


INSERT INTO CONJUGACAO (ID,IDVERBO,IDTEMPO)
VALUES(4, 1, 4);

INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(4, 1, 'fora');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(4, 2, 'foras');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(4, 3, 'fora');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(4, 4, 'fôranos');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(4, 5, 'fôreis');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(4, 6, 'foram');


INSERT INTO CONJUGACAO (ID,IDVERBO,IDTEMPO)
VALUES(5, 1, 5);

INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(5, 1, 'serei');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(5, 2, 'serás');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(5, 3, 'será');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(5, 4, 'seremos');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(5, 5, 'sereis');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(5, 6, 'serão');


INSERT INTO CONJUGACAO (ID,IDVERBO,IDTEMPO)
VALUES(6, 1, 6);

INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(6, 1, 'seria');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(6, 2, 'serias');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(6, 3, 'seria');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(6, 4, 'seríamos');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(6, 5, 'seríeis');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(6, 6, 'seriam');


INSERT INTO CONJUGACAO (ID,IDVERBO,IDTEMPO)
VALUES(7, 1, 7);

INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(7, 1, 'seja');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(7, 2, 'sejas');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(7, 3, 'seja');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(7, 4, 'sejamos');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(7, 5, 'sejais');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(7, 6, 'sejam');


INSERT INTO CONJUGACAO (ID,IDVERBO,IDTEMPO)
VALUES(8, 1, 8);

INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(8, 1, 'fosse');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(8, 2, 'fosses');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(8, 3, 'fosse');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(8, 4, 'fôssemos');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(8, 5, 'fôsseis');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(8, 6, 'fossem');


INSERT INTO CONJUGACAO (ID,IDVERBO,IDTEMPO)
VALUES(9, 1, 9);

INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(9, 1, 'for');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(9, 2, 'fores');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(9, 3, 'for');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(9, 4, 'formos');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(9, 5, 'fordes');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(9, 6, 'forem');


INSERT INTO CONJUGACAO (ID,IDVERBO,IDTEMPO)
VALUES(10, 1, 10);

INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(10, 2, 'sê');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(10, 7, 'seja');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(10, 4, 'sejamos');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(10, 5, 'sede');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(10, 8, 'sejam');


INSERT INTO CONJUGACAO (ID,IDVERBO,IDTEMPO)
VALUES(11, 1, 11);

INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(11, 2, 'sejas');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(11, 7, 'seja');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(11, 4, 'sejamos');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(11, 5, 'sejais');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(11, 8, 'sejam');


INSERT INTO CONJUGACAO (
    ID,IDVERBO,IDTEMPO)
VALUES(12, 1, 12);

INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(12, NULL, 'ser');


INSERT INTO CONJUGACAO (ID,IDVERBO,IDTEMPO)
VALUES(13, 1, 13);

INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(13, 1, 'ser');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(13, 2, 'seres');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(13, 3, 'ser');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(13, 4, 'sermos');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(13, 5, 'serdes');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(13, 6, 'serem');


INSERT INTO CONJUGACAO (ID,IDVERBO,IDTEMPO)
VALUES(14, 1, 14);

INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(14, NULL, 'sendo');


INSERT INTO CONJUGACAO (ID,IDVERBO,IDTEMPO)
VALUES(15, 1, 15);

INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(15, NULL, 'sido');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(15, NULL, 'sida');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(15, NULL, 'sidos');
INSERT INTO FORMA(IDCONJUGACAO,IDPESSOA,TEXTO)
VALUES(15, NULL, 'sidas');
