INSERT INTO MODO(ID, CODIGO, DESCRICAO)
VALUES( 1, 'INDICATIVO', 'Indicativo');

INSERT INTO MODO(ID, CODIGO, DESCRICAO)
VALUES( 2, 'SUBJUNTIVO', 'Subjuntivo');


INSERT INTO TEMPO(ID, CODIGO, DESCRICAO, IDMODO, TEXTOFORMATO)
VALUES( 1, 'PRESENTE', 'Presente', 1, '${PESSOA} ${VERBO}');

INSERT INTO TEMPO(ID, CODIGO, DESCRICAO, IDMODO, TEXTOFORMATO)
VALUES( 2, 'PRETERITO_IMPERFEITO', 'Pretérito Imperfeito', 1, '${PESSOA} ${VERBO}');

INSERT INTO TEMPO(ID, CODIGO, DESCRICAO, IDMODO, TEXTOFORMATO)
VALUES( 3, 'PRETERITO_PERFEITO', 'Pretérito Perfeito', 1, '${PESSOA} ${VERBO}');

INSERT INTO TEMPO(ID, CODIGO, DESCRICAO, IDMODO, TEXTOFORMATO)
VALUES( 4, 'PRETERITO_MAIS_QUE_PERFEITO', 'Pretérito Mais Que Perfeito', 1, '${PESSOA} ${VERBO}');

INSERT INTO TEMPO(ID, CODIGO, DESCRICAO, IDMODO, TEXTOFORMATO)
VALUES( 5, 'FUTURO_DO_PRESENTE', 'Futuro do Presente', 1, '${PESSOA} ${VERBO}');

INSERT INTO TEMPO(ID, CODIGO, DESCRICAO, IDMODO, TEXTOFORMATO)
VALUES( 6, 'FUTURO_DO_PRETERITO', 'Futuro do Pretérito', 1, '${PESSOA} ${VERBO}');

INSERT INTO TEMPO(ID, CODIGO, DESCRICAO, IDMODO, TEXTOFORMATO)
VALUES( 7, 'PRESENTE_DO_SUBJUNTIVO', 'Presente', 2, 'Que ${PESSOA} ${VERBO}');

INSERT INTO TEMPO(ID, CODIGO, DESCRICAO, IDMODO, TEXTOFORMATO)
VALUES( 8, 'PRETERITO_IMPERFEITO_DO_SUBJUNTIVO', 'Pretérito', 2, 'Se ${PESSOA} ${VERBO}');

INSERT INTO TEMPO(ID, CODIGO, DESCRICAO, IDMODO, TEXTOFORMATO)
VALUES( 9, 'FUTURO_DO_SUBJUNTIVO', 'Futuro', 2, 'Quando ${PESSOA} ${VERBO}');

INSERT INTO TEMPO(ID, CODIGO, DESCRICAO, IDMODO, TEXTOFORMATO)
VALUES( 10, 'IMPERATIVO_AFIRMATIVO', 'Imperativo Afirmativo', NULL, '${VERBO} ${PESSOA}');

INSERT INTO TEMPO(ID, CODIGO, DESCRICAO, IDMODO, TEXTOFORMATO)
VALUES( 11, 'IMPERATIVO_NEGATIVO', 'Imperativo Negativo', NULL, 'Não ${VERBO} ${PESSOA}');

INSERT INTO TEMPO(ID, CODIGO, DESCRICAO, IDMODO, TEXTOFORMATO)
VALUES( 12, 'INFINITIVO_IMPESSOAL', 'Infinitivo Impessoal', NULL, '${VERBO}');

INSERT INTO TEMPO(ID, CODIGO, DESCRICAO, IDMODO, TEXTOFORMATO)
VALUES( 13, 'INFINITIVO_PESSOAL', 'Infinitivo Pessoal', NULL, '${PESSOA} ${VERBO}');

INSERT INTO TEMPO(ID, CODIGO, DESCRICAO, IDMODO, TEXTOFORMATO)
VALUES( 14, 'GERUNDIO', 'Gerúndio', NULL, '${VERBO}');

INSERT INTO TEMPO(ID, CODIGO, DESCRICAO, IDMODO, TEXTOFORMATO)
VALUES( 15, 'PARTICIPIO_PASSADO', 'Particípio Passado', NULL, '${VERBO}');


INSERT INTO PESSOA(ID, ORDEM, CODIGO, DESCRICAO)
VALUES(1, 1, 'EU', 'Eu');

INSERT INTO PESSOA(ID, ORDEM, CODIGO, DESCRICAO)
VALUES(2, 2, 'TU', 'Tu');

INSERT INTO PESSOA(ID, ORDEM, CODIGO, DESCRICAO)
VALUES(3, 3, 'ELE', 'Ele');

INSERT INTO PESSOA(ID, ORDEM, CODIGO, DESCRICAO)
VALUES(4, 4, 'NOS', 'Nós');

INSERT INTO PESSOA(ID, ORDEM, CODIGO, DESCRICAO)
VALUES(5, 5, 'VOS', 'Vós');

INSERT INTO PESSOA(ID, ORDEM, CODIGO, DESCRICAO)
VALUES(6, 6, 'ELES', 'Eles');

INSERT INTO PESSOA(ID, ORDEM, CODIGO, DESCRICAO)
VALUES(7, 3, 'VOCE', 'Você');

INSERT INTO PESSOA(ID, ORDEM, CODIGO, DESCRICAO)
VALUES(8, 6, 'VOCES', 'Vocês');
