service: verbos-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: sa-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'